version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: linkU-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: linkUDB
      POSTGRES_USER: linkU
      POSTGRES_PASSWORD: linkU1234
      TZ: Asia/Seoul
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: linkU-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    restart: unless-stopped
volumes:
  postgres_data:
  redis_data:
