# Discord 알림 채널 정의
apiVersion: 1

contactPoints:
  - orgId: 1
    name: discord-alerts
    receivers:
      - uid: discord-alerts-receiver
        type: discord
        settings:
          use_discord_username: true
          url: __DISCORD_ALERT_WEBHOOK_URL__
        disableResolveMessage: false
