spring:
  config:
    import: optional:file:/app/config/application-secret.properties
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/seed
      - classpath:db/local

fcm:
  credentials:
    path: file:/app/config/linku-firebase-adminsdk.json

logging:
  level:
    root: INFO
    com.umc.linkyou: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
