-- ============ 1. 테스트 계정 13개 ============
INSERT INTO users (user_id, nick_name, password, role, status, job_id, created_at, updated_at) VALUES (101, 'seed_lang_learner', '$2b$12$auCAmviSO58zXW2roqtSj.ASzpINp7F5GyaOtL9ZauTIYEQwEhHFK', 'USER', 'ACTIVE', 2, now(), now()) ON CONFLICT (user_id) DO NOTHING;
INSERT INTO users (user_id, nick_name, password, role, status, job_id, created_at, updated_at) VALUES (102, 'seed_studymethod', '$2b$12$auCAmviSO58zXW2roqtSj.ASzpINp7F5GyaOtL9ZauTIYEQwEhHFK', 'USER', 'ACTIVE', 1, now(), now()) ON CONFLICT (user_id) DO NOTHING;
INSERT INTO users (user_id, nick_name, password, role, status, job_id, created_at, updated_at) VALUES (103, 'seed_it_dev', '$2b$12$auCAmviSO58zXW2roqtSj.ASzpINp7F5GyaOtL9ZauTIYEQwEhHFK', 'USER', 'ACTIVE', 3, now(), now()) ON CONFLICT (user_id) DO NOTHING;
INSERT INTO users (user_id, nick_name, password, role, status, job_id, created_at, updated_at) VALUES (104, 'seed_selfdev', '$2b$12$auCAmviSO58zXW2roqtSj.ASzpINp7F5GyaOtL9ZauTIYEQwEhHFK', 'USER', 'ACTIVE', 3, now(), now()) ON CONFLICT (user_id) DO NOTHING;
INSERT INTO users (user_id, nick_name, password, role, status, job_id, created_at, updated_at) VALUES (105, 'seed_career', '$2b$12$auCAmviSO58zXW2roqtSj.ASzpINp7F5GyaOtL9ZauTIYEQwEhHFK', 'USER', 'ACTIVE', 6, now(), now()) ON CONFLICT (user_id) DO NOTHING;
INSERT INTO users (user_id, nick_name, password, role, status, job_id, created_at, updated_at) VALUES (106, 'seed_biz_insight', '$2b$12$auCAmviSO58zXW2roqtSj.ASzpINp7F5GyaOtL9ZauTIYEQwEhHFK', 'USER', 'ACTIVE', 3, now(), now()) ON CONFLICT (user_id) DO NOTHING;
INSERT INTO users (user_id, nick_name, password, role, status, job_id, created_at, updated_at) VALUES (107, 'seed_lifestyle', '$2b$12$auCAmviSO58zXW2roqtSj.ASzpINp7F5GyaOtL9ZauTIYEQwEhHFK', 'USER', 'ACTIVE', 5, now(), now()) ON CONFLICT (user_id) DO NOTHING;
INSERT INTO users (user_id, nick_name, password, role, status, job_id, created_at, updated_at) VALUES (108, 'seed_psych', '$2b$12$auCAmviSO58zXW2roqtSj.ASzpINp7F5GyaOtL9ZauTIYEQwEhHFK', 'USER', 'ACTIVE', 6, now(), now()) ON CONFLICT (user_id) DO NOTHING;
INSERT INTO users (user_id, nick_name, password, role, status, job_id, created_at, updated_at) VALUES (109, 'seed_essay_column', '$2b$12$auCAmviSO58zXW2roqtSj.ASzpINp7F5GyaOtL9ZauTIYEQwEhHFK', 'USER', 'ACTIVE', 5, now(), now()) ON CONFLICT (user_id) DO NOTHING;
INSERT INTO users (user_id, nick_name, password, role, status, job_id, created_at, updated_at) VALUES (110, 'seed_trend', '$2b$12$auCAmviSO58zXW2roqtSj.ASzpINp7F5GyaOtL9ZauTIYEQwEhHFK', 'USER', 'ACTIVE', 3, now(), now()) ON CONFLICT (user_id) DO NOTHING;
INSERT INTO users (user_id, nick_name, password, role, status, job_id, created_at, updated_at) VALUES (111, 'seed_travel_food', '$2b$12$auCAmviSO58zXW2roqtSj.ASzpINp7F5GyaOtL9ZauTIYEQwEhHFK', 'USER', 'ACTIVE', 4, now(), now()) ON CONFLICT (user_id) DO NOTHING;
INSERT INTO users (user_id, nick_name, password, role, status, job_id, created_at, updated_at) VALUES (112, 'seed_etc', '$2b$12$auCAmviSO58zXW2roqtSj.ASzpINp7F5GyaOtL9ZauTIYEQwEhHFK', 'USER', 'ACTIVE', 3, now(), now()) ON CONFLICT (user_id) DO NOTHING;
INSERT INTO users (user_id, nick_name, password, role, status, job_id, created_at, updated_at) VALUES (113, 'seed_media_culture', '$2b$12$auCAmviSO58zXW2roqtSj.ASzpINp7F5GyaOtL9ZauTIYEQwEhHFK', 'USER', 'ACTIVE', 3, now(), now()) ON CONFLICT (user_id) DO NOTHING;
